import type { Metadata } from "next";
import Image from "next/image";
import { CTASection, PageIntro } from "@/components/ui";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("Despre EVEMARSERVICE", "EVEMARSERVICE produce mobilier la comandă din 2020, în Răstoaca, Vrancea, cu servicii complete de proiectare, producție, transport și montaj.", "/despre-noi");

export default function AboutPage() {
  return <><PageIntro title="Mobilier personalizat, realizat cu grijă pentru întregul spațiu." lead="EVEMARSERVICE activează din 2020 în Răstoaca, județul Vrancea, și realizează mobilier la comandă în producție proprie." /><section className="section"><div className="shell about-story"><div className="about-story__copy"><h2>Lucrăm de la spațiul real</h2><p>Nu pornim de la un produs standard, ci de la dimensiunile, preferințele și bugetul fiecărui client. Măsurătorile și proiectarea 3D ne ajută să clarificăm soluția înainte de producție.</p><p>Punem accent pe calitatea execuției și pe detaliile care fac mobilierul ușor de folosit zi de zi. După producție, asigurăm transportul și montajul la locația clientului.</p></div><div className="about-story__images"><div><Image src="/images/portfolio/bucatarie/774196863_1695029662627501_3665270524665365688_n.jpg" alt="Bucătărie EVEMARSERVICE cu lemn și fronturi închise" fill sizes="(max-width: 800px) 90vw, 38vw" /></div><div><Image src="/images/portfolio/living/490339896_1245387024258436_3330696480927201931_n.jpg" alt="Mobilier de living realizat la comandă de EVEMARSERVICE" fill sizes="(max-width: 800px) 60vw, 24vw" /></div></div></div></section><section className="section section--dark"><div className="shell about-values"><article><strong>Din 2020</strong><p>Experiență în realizarea mobilierului personalizat.</p></article><article><strong>Producție proprie</strong><p>Execuție controlată în unitatea EVEMARSERVICE.</p></article><article><strong>De la A la Z</strong><p>De la prima discuție până la transport și montaj.</p></article></div></section><section className="section"><div className="shell area-note"><h2>Lucrăm în Vrancea și în zonele învecinate</h2><p>Preluăm proiecte în județul Vrancea și în județele apropiate. Pentru alte localități, posibilitatea colaborării depinde de distanță și de caracteristicile proiectului.</p></div></section><CTASection /></>;
}
